#!/bin/bash 

# post-commit: Hook used for SVN post commits
#
# Hank Wethington 

# This script is set to publish information after SVN commits to HipChat. 
#
# Place this file in your SVN repository hooks directory.
# Required files/Application/services:
#     * hipchat_room_message:  https://github.com/hipchat/hipchat-cli
#     * Subversion: http://subversion.tigris.org/
#     * Working repository
#     * HipChat account and room setup: https://www.hipchat.com/
#     * HipChat token created: https://www.hipchat.com/groups/api
#

# Set hipchat_cli info
#
HCCLI="<LOCATION OF hipchat-cli>"
TOKEN="<TOKEN>"
ROOM="<ROOM>"
USER="<USER>"

# Sub-Repository - USE "" if no sub-repo is needed
SUB=""

# svnlook location
LOOK="<svnlook LOCATION>"

# Temp file location and name
HCTMP="<TMP FILE>"

##############################################################
##############################################################
############ Edit below at your own risk #####################
##############################################################
##############################################################

# Check that we are using the scipt correctly
# Shouldn't be an issue unless you're running this by hand
usage(){
  echo ""
  echo "Usage: $0 REPO REVISION"
  echo ""
}

# Check the command line args
# Shouldn't be an issue unless you're running this by hand
if [ $# -ne 2 ] 
then
  usage
  exit 1
fi

# Setup the actual post-commit process
post(){
  echo "`${WHO}` updated ${REPO} to Rev: ${REV}" > ${HCTMP}
  echo "`${CMT}`" >> ${HCTMP}
  echo "The following list of files were changed:" >> ${HCTMP}
  echo "`${FILES}`" >> ${HCTMP}
# Added test to look for specific sub-repositories
if [ -n "$SUB" ]
then
CHKSUB=`grep ${SUB} ${HCTMP} | wc -l` 
  if [ $CHKSUB -gt 0 ]
  then
  cat ${HCTMP} | ${HCCTL}
  rm -f ${HCTMP}
  else
  rm -f ${HCTMP}
  fi
else
  cat ${HCTMP} | ${HCCTL}
  rm -f ${HCTMP}
fi
}

# Make things tight
# $1 and $2 are passed by the "svn commit" process
# CMT, WHO and FILES are set to keep the "post" process tight and easy
# HCCTL is the call to the hipchat_cli
REPO="$1"
REV="$2"
CMT="${LOOK} log ${REPO}"
WHO="${LOOK} author ${REPO}"
FILES="${LOOK} changed ${REPO}"
HCCTL="${HCCLI} -t ${TOKEN} -r ${ROOM} -f ${USER}"

# Finally, let's do what needs to be done.
post
